"""Add status to Product

Revision ID: acec9e1d0922
Revises: 94476ed68a66
Create Date: 2025-09-27 12:31:09.894438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acec9e1d0922'
down_revision = '94476ed68a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table('products', schema=None) as batch_op:
    batch_op.add_column(
        sa.Column('status', sa.String(length=50), nullable=False, server_default='active')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###