name: Backend CI/CD (Render)

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  backend:
    name: Backend (Flask)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend dependencies
        run: pip install -r server/requirements.txt

      - name: Run backend tests with pytest
        run: pytest


  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [backend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

